package com.obtuse.util;

/*
 * Copyright © 2015 Obtuse Systems Corporation
 */

/**
 * Generate unique int ids within some id-space.
 */

public interface UniqueIntegerIdGenerator {

    /**
     * Generate an int id which is different than any other ids generated by separate invocations of this method on
     * this instance.
     * <p/>Implementations of this method should be thread safe.
     * @return an int id which is unique from the perspective of this instance.
     */

    int getUniqueId();

}
